#!/usr/bin/env lua

local day = arg[1]
local input_file = day .. '/input.txt'

package.path = package.path .. ';lib/?.lua' .. string.format(';%s/?.lua', day)
local s = require('solution')

local p1 = s.part1(input_file)
print('Part 1: ' .. p1)
assert(p1 == s.solution_part1)

local p2 = s.part2(input_file)
print('Part 2: ' .. p2)
assert(p2 == s.solution_part2)
